### ISSUE TITLE
Tasks for Intro to Data Science Course

### ISSUE THREAD

**Issue by juliaphilipp** [biocswirl-dev-team/BiocSwirl_Intro_to_Data_Science#4]
# [biocswirl] (Task for Intro to Data Science Course) <subject> 

# Tasks 
- [x] complete lab01
- [x] complete lab02
- [ ] what is left to do in lab03?
- [ ] complete lab03
- [ ] complete lab04 (currently at `tidyr`)
- [x]  lab05 outline - created all question templates
- [ ] complete lab05 questions/answers/hints (some Qs need filling in, Q16-22,51)
- [ ] add visualizations to lab05
- [x] test_course()
- [ ] demo_lessons() - ongoing, as I'm finishing the labs
- [x] pack_course() - preliminarily done, so others can start testing, too
- [ ] install_course() & demo locally - ongoing, as I'm finishing the labs
- [ ] install_course() & demo on other computer - need testers!
- [ ] add course to BiocSwirl R package

# Resources
Course based on [Bruno Grande MBB343 - lab 01-lab05](https://github.com/BrunoGrandePhD/MBB343/tree/c2bebf3f75035a964cf347751bc0fe35bbd87bae)

# Tag can be 
    biocswirl(related to course material)
    biocterm (interface changes)
    dev      (developers only)
    file     (changes to file and folder structuring) 
    rpkg     (r package/usethis and CRAN documentation changes)
    feat     (new feature)
    fix      (bug fix)
    refactor (refactoring code)
    style    (formatting, missing semi colons, etc; no code change)
    doc      (changes to documentation)
    test     (adding or refactoring tests; no production code change)
    version  (version bump/new release; no production code change)
    dbg      (Changes in debugging code/frameworks; no production code change)
    license  (Edits regarding licensing; no production code change)
    hack     (Temporary fix to make things move forward; please avoid it)
    WIP      (Work In Progress; for intermediate commits to keep patches reasonably sized)
